language: cpp
cache:
  directories:
before_script:
- if [ -d Bluespec-2018.10.beta1 ] ; then echo bluespec cached; else curl http://buildbot.connectal.org/downloads/Bluespec-2018.10.beta1.tar.gz | tar -zxf - ; fi
- mkdir -p lib
- ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 lib/libgmp.so.3
- if [ "$CONNECTAL_ARCH" == "cvc" ]; then if [ -d open-src-cvc-700c-1 ] ; then echo cvc cached; else curl -L https://github.com/cambridgehackers/open-src-cvc/archive/700c-1.tar.gz | tar -zxf - ; (cd open-src-cvc-700c-1/src; make -j4 -f makefile.cvc64); fi; fi
- (if [ "$CONNECTAL_ARCH" == "verilator" ]; then curl -L http://www.veripool.org/ftp/verilator-3.888.tgz | tar -zxf -; cd verilator-3.888/; ./configure --prefix=`dirname $PWD`/verilator; make -j4;  make install; fi)
- curl http://www.dabeaz.com/ply/ply-3.9.tar.gz | tar -zxf -
- ln -s ../ply-3.9/ply scripts
- ls -l scripts/ply
env:
  global:
    - BLUESPECDIR=$PWD/Bluespec-2018.10.beta1/lib
    - PATH=$PATH:$PWD/Bluespec-2018.10.beta1/bin:$PWD/open-src-cvc-700c-1/src:$PWD/verilator/bin
    - LD_LIBRARY_PATH=$PWD/lib
  matrix:
    - CONNECTAL_TEST=examples/echo CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/echopy CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/echo CONNECTAL_ARCH=cvc
    - CONNECTAL_TEST=examples/echopy CONNECTAL_ARCH=cvc
    - CONNECTAL_TEST=examples/echoslow CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/echoslow CONNECTAL_ARCH=cvc
    - CONNECTAL_TEST=examples/simple CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=examples/simple CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/simple CONNECTAL_ARCH=cvc
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=cvc
    - CONNECTAL_TEST=examples/strstr CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=tests/memserver_write128 CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=tests/memserver_copy128 CONNECTAL_ARCH=verilator
script:
- export PYTHONPATH=$PWD/scripts; make scripts/syntax/parsetab.py; cd $CONNECTAL_TEST; make build.$CONNECTAL_ARCH run.$CONNECTAL_ARCH
sudo: no
dist: trusty
os:
- linux
addons:
  apt:
    sources:
    - sourceline: 'ppa:jamey-hicks/connectal'
    packages:
    - python-dev
    - libgmp10
    - libjsoncpp-dev
    - flex
    - bison
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#connectal

  slack:
    secure: mQApKri2F2TZEyLEs530x+snMA8aDdL6o0e/HCVqk3t4pfSfj2OfPQ5edVrvIh+dsFjhX1GNDk94LSmZTS6AVCQ4+VPXORN1VjvB+xIeyP/PsIjSUoWqvS2V0t8CYV5K+5HRJq2H7tNmY4wxZYQnPAAGplsrKgJBxjccMhSqO30=
